//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_PistolGun : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Shoot
        {
            get
            {
                return SteamVR_Actions.pistolGun_Shoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean ReleasePistol
        {
            get
            {
                return SteamVR_Actions.pistolGun_ReleasePistol;
            }
        }
        
        public virtual SteamVR_Action_Boolean NextBullet
        {
            get
            {
                return SteamVR_Actions.pistolGun_NextBullet;
            }
        }
        
        public virtual SteamVR_Action_Boolean PreviousBullet
        {
            get
            {
                return SteamVR_Actions.pistolGun_PreviousBullet;
            }
        }
    }
}
